#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-defaults
Version  : 0.2.4
Release  : 13
URL      : https://files.pythonhosted.org/packages/1c/71/6c47f016f25828f028d6eedd2ddccc216afac04bf3b9cc8777e8be88556f/colcon-defaults-0.2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/1c/71/6c47f016f25828f028d6eedd2ddccc216afac04bf3b9cc8777e8be88556f/colcon-defaults-0.2.4.tar.gz
Summary  : Extension for colcon to read defaults from a config file.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-defaults-python = %{version}-%{release}
Requires: colcon-defaults-python3 = %{version}-%{release}
Requires: PyYAML
Requires: colcon-core
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : colcon-core

%description
colcon-defaults
===============
An extension for `colcon-core <https://github.com/colcon/colcon-core>`_ to provide custom default values for the command line arguments from a configuration file.

%package python
Summary: python components for the colcon-defaults package.
Group: Default
Requires: colcon-defaults-python3 = %{version}-%{release}

%description python
python components for the colcon-defaults package.


%package python3
Summary: python3 components for the colcon-defaults package.
Group: Default
Requires: python3-core
Provides: pypi(colcon_defaults)
Requires: pypi(colcon_core)
Requires: pypi(pyyaml)

%description python3
python3 components for the colcon-defaults package.


%prep
%setup -q -n colcon-defaults-0.2.4
cd %{_builddir}/colcon-defaults-0.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584058870
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
